### ISSUE TITLE
apk build

### ISSUE THREAD

**Issue by rui-cruz** [sfeather/nativescript-kitchensink#2]
Hi,

Is there any apk for testing right away on device? It would be helpful if you add a release folder with ipa and apk if possible..

Regards

**Comment by sfeather** [comment]
Short answer: no.
Long answer: No. An iOS ipa wouldn't be useful to anyone who downloaded it as it would not have a provisioning profile allowing it to be installed. An apk, no. Not supporting a binary and the pain points that would come from that.
